### ISSUE TITLE
Rhino - Blender: Materials on meshes change on re-import on new versions of the same mesh.

### ISSUE THREAD

**Issue by WriteView11** [specklesystems/speckle-blender#102]
So when I upload native rhino geometry and download it in blender, textures/materials assigned in blenders change. However if I convert Rhino geometry to mesh and then upload it and download it in blender (assigned) materials stay the same. It is really inconvenient to convert everything to mesh every time I upload...

**Comment by JR-Morgan** [comment]
Hi @WriteView11 Please could you test our new 2.13 release. 
I'm hoping this issue will now be fixed for you.
When you have the time, please could you check it out so we can close this issue.
