### ISSUE TITLE
🚚 Move modules folder into bpy_speckle

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-blender#122]
## Description

While skimming over the Blenderkit plugin, something caught my attention: `Dependencies` folder was located within the `blenderkit` folder. For our connector, there is `bpy_speckle` folder and also a folder called `modules`. If I’m not mistaken (correct me if I'm wrong), this folder only contains the dependencies of the speckle plugin. 

### What does this cause?

- When users want to install our connector on a Blender version that we do not support, they just copy the `bpy_speckle` folder (normally). It's confusing that they also need to copy the `modules` folder.
- It would be also nice to have everything in one place.

### If…

this is done for security reasons or to keep dependencies up to date and there is no other solution, please ignore this enhancement.

## Screenshots

![explorer_kfFRno3MUQ](https://user-images.githubusercontent.com/51519350/197118283-5403a420-dbf6-4f57-8c92-18aa73109d41.gif)

**Comment by bimgeek** [comment]
@tsvilans do you know why our folder structure is organized this way 🤔?

**Comment by tsvilans** [comment]
@bimgeek the `modules` folder is pretty standard for many user-added add-ons. A quick test shows that it could actually live in the folder above, in `scripts`, next to `addons`, not inside of it. It's a way of differentiating what is an add-on and what are dependencies for add-ons, some of which might be shared.

You'll notice the same structure in the main Blender directory (`C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts` -> `addons`, `modules`, `presets`, etc.)

I'm not familiar with `blenderkit`, not sure why they have their own `dependencies` folder...

I think the add-on itself should take care of installing the correct dependencies to the modules folder. I thought this was already the case: if importing all the `speckle` dependencies fails, it should run `pip install` to ensure that they are installed correctly.

**Comment by tsvilans** [comment]
Come to think, I think we did that for the Rhino add-on instead... 

Take a look at https://github.com/jesterKing/import_3dm/blob/master/import_3dm/read3dm.py to see how that looks. If it can't find `rhino3dm`, it tries to install it, so you don't need to bundle it with the add-on and therefore don't need a bunch of different bundled versions of the add-on.

**Comment by tsvilans** [comment]
See this answer for possibly a more elegant solution that gives the user explicit control over installing dependencies: https://blender.stackexchange.com/a/168482

**Comment by JR-Morgan** [comment]
https://github.com/specklesystems/speckle-blender/pull/146
alternative implemented
