### ISSUE TITLE
bug: speckle connector doesn't install to fresh installations of Blender 

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-blender#127]
## Description

`%AppData%\Blender Foundation\Blender\version\scripts\addons` is the folder where Speckle connector lives. This folder is not created when a fresh installation of Blender takes place. And if the first plugin you want to install is the Speckle connector, the installation does not happen because Manager cannot see this folder. This problem would be solved automatically if we enable the installation via zip.

## Expected Behaviour

Successful installation of Speckle connector even when its the first plugin users install.
## Steps to reproduce

1. Install a version of Blender that is not installed on your computer.
2. Install Speckle connector.
3. Open Blender.
4. Try to find Speckle in the list of add-ons. It will not be there.
5. Go to %appdata%/Blender Foundation/Blender. Try to find the folder of the version you installed.

**Comment by JR-Morgan** [comment]
Cannot reproduce, Lets make sure we test this as part of 2.10 testing.

**Comment by Marco-Pellegrino** [comment]
Hi Guys,

I had the same issue.

Thanks for solving it @bimgeek

**Comment by JR-Morgan** [comment]
This issue only occurs with fresh installations of blender.
On a fresh install, blender doesn't generate the `%appdata%\Blender Foundation\Blender\{ver}` folder. 

Once the user saves a file, or saves a userpref, this dir structure is created.
For now, there's no clear fixes we can do, other than document this behaviour.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
