### ISSUE TITLE
bug: Plugin not working on macOS

### ISSUE THREAD

**Issue by coryoso** [specklesystems/speckle-blender#139]
### Expected vs. Actual Behavior

When installing the plugin (either manually or from the manager) it cannot be enabled due to not finding `host_applications` in speckleapi. I removed the import as it is only used for metrics and now it is working. It should work without manual intervention though.

### Reproduction Steps & System Config (win, osx, web, etc.)

macOS Ventura, Blender 3.3 and 3.4, newest Speckle version. Installed via manager or manually by building from source, failed when enabling. 

### Proposed Solution (if any)

Maybe it is not available on newer macs? So maybe check if its available and if not disregard it's use. I can help you!

**Comment by JR-Morgan** [comment]
@coryoso could you try the `2.11.0-alpha.3` alpha version that was pushed today with some major changes to our mac installers.
Hopefully this should fix all issues with installation

**Comment by coryoso** [comment]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/1223336/208140403-401d9722-6d06-4f5c-bbfd-f0edbb6971ab.png">

Nope, latest beta for manager and blender. Also uploaded a simple box from grasshopper which is not even showing up correctly in the web viewer. Sad, would love to use it.

**Comment by gjedlicska** [comment]
We've fixed this in `2.11`
