### ISSUE TITLE
Deployment via Manager

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-blender#15]

**Comment by teocomi** [comment]
Ok, so I looked a bit into this and seems fairly simple (last famous words), here are the steps I suggest taking:

- start off an existing connector installer
- add the files that need to be copied locally on the user machine in `[Files]`
- add a `[Run]` section with code to install the pip packages needed 
- create a CI script for the blender repo to run the installer script and upload the artifact to DO (same as for speckle sharp)

Let me know when you get to this and I can walk you through the iss/CI stuff!

**Comment by izzylys** [comment]
done & dusted 🥳
