### ISSUE TITLE
🗺 BlenderGIS → Speckle

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-blender#162]
Related to this forum discussion https://speckle.community/t/blender-to-qgis-georeferencing-not-working/5699/10

Let's investigate how we can support the BlenderGIS -> QGIS workflow better.

@KatKatKateryna and @JR-Morgan have done a little scoping on this.
Let's look into the possibility of sending CRS data on the root commit object from the SRID given to us by BlenderGIS imported shape files.

TODO: 
- [ ] Move CRS class to SpecklePY
- [ ] Implement CRS class in Sharp also?
- [ ] Blender commits send CRS data
- [ ] QGIS connector can read this CRS data

**Comment by KatKatKateryna** [comment]
Related: https://github.com/specklesystems/specklepy/issues/274

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
