### ISSUE TITLE
Blender 4 support

### ISSUE THREAD

**Issue by MatusGasparik** [specklesystems/speckle-blender#184]
I realized that the connector only support Blender 3.X. There is a mention that there is an experimental support for the version 4 but I can't find any instructions. Also, what is the longer-term perspective for the version 4 support?

**Comment by JR-Morgan** [comment]
Simply install via [Speckle Manager or through our manual installers ](https://releases.speckle.systems/). We currently will install to Blender 3.0 - 4.1.
For more instructions, [see our docs](https://speckle.guide/user/blender.html) and [tutorial video](https://www.youtube.com/watch?v=tvSAaflRwOM).

We have been describing Blender 4.X as experimental only in-so-far as we test our connector more rigorously with the latest LTS version of blender (Currently Blender 3.6).
However we've done a fair bit of testing on Blender 4.0 as well, and everything appears to be working. 

Any problems or bugs, please don't hesitate to file a bug report.

**Comment by JR-Morgan** [comment]
Closing this issue for now, since Blender 4 is fully supported. We'll update the messaging to removed the "experimental" word after our next release.
