### ISSUE TITLE
Recovery of commit selection doesn't work if the user hasn't explicitly selected a branch

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-blender#204]
If the user hasn't explicitly set a branch, and instead they let it default to `main`,
then the branch/commit recovery does not work. 

Case 1: working as expected
1. Select a branch from the drop down (any branch, even the already selected "main", but you must select one explicitly)
2. Select a commit that isn't the latest one
3. Refresh stream
4. Observe, selection has persisted as expected

Case 2: not working as expected, branch & commit selection reset to main+latest
1. Select a commit that isn't the latest one
2. Refresh stream
3. Observe, selection has been changed to latest commit

**Comment by JR-Morgan** [comment]
@overengineer any chance you're interested in taking a look at this issue?

If not, no worries, I'm happy to take a look.
Ideally we'd fix this before making the 2.20 release so this one is higher priority than #205 or #200

**Comment by overengineer** [comment]
I fixed this bug with https://github.com/specklesystems/speckle-blender/commit/1993180e52b0f4abf746e3edc60f9eb9ec20c236

**Comment by JR-Morgan** [comment]
@overengineer amazing thank you, do you mind making a PR

**Comment by overengineer** [comment]
#206
