### ISSUE TITLE
Recovery of branch selection doesn't work after a send operation

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-blender#205]
As part of the send operation, the last step refreshes the UI so that the commit just sent displays in the UI

The branch recovery feature introduced by #196 doesn't work for this case...

Steps to reproduce:

1. Select a branch
2. Select objects & send
3. observe branch gets set to `main` after send

**Comment by JR-Morgan** [comment]
![Blender bug report](https://github.com/user-attachments/assets/f5598891-5a8b-477f-b7f4-0ddcb96b877e)

**Comment by JR-Morgan** [comment]
![Blender bug report](https://github.com/user-attachments/assets/d6d1b745-6c8c-49fc-8f13-3b6ea6c45e37)

A more detailed steps to reproduce:
 - From the list of Speckle projects, select a project that isn't the first project
 - Send an object to a said project
 - Observe, that the selection is in an invalid state, where no models appear in the drop down, and trying to receive leads to an unhandled exception

**Comment by JR-Morgan** [comment]
@overengineer are you interested in trying to find a fix,
again, no worries if you're busy, but please let me know.

**Comment by overengineer** [comment]
Imma look into it

**Comment by overengineer** [comment]
Selected commit should change to the new commit after send operation, right?

**Comment by JR-Morgan** [comment]
ideally, yes
