### ISSUE TITLE
Sending Rhino Breps results in empty in blender

### ISSUE THREAD

**Issue by rheinason** [specklesystems/speckle-blender#27]
### Expected vs. Actual Behavior

Sending brep from Rhino into blender should results in a DisplayMesh showing in Blender, right? 

### Reproduction Steps & System Config (win, osx, web, etc.)

Create a Brep in Rhino, send via Speckle.

**Comment by izzylys** [comment]
hey @rheinason, thanks a lot for reporting this! i've had a look and it seems we weren't checking for this properly (sometimes there's a `displayMesh` and sometimes there's a `displayValue`). merging a fix now and it should be resolved in v 2.1.2 🚀 

however, let me know if you're still having issues and we can reopen this and have another look
