### ISSUE TITLE
🔘 Toggle modifiers on send

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-blender#36]
Currently, modifiers need to be applied in order to send. We should investigate if we can have a toggle to apply the modifier to the sent model without applying it in Blender. 

from [the forum](https://speckle.community/t/support-for-modifiers/1401/3?u=izzylys)

**Comment by tsvilans** [comment]
Agreed! Could be a simple radiobox / toggle in the `Send` settings...
