### ISSUE TITLE
🏗 Built Elements - do we want to support their creation?

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-blender#5]
SpecklePy doesn't have these obj models yet, but they are coming. Should support exist for creating "Built Elements" in Blender? Is there a need for the people who use Blender to get things into Revit, or is it not a relevant use case to support.

**Comment by tsvilans** [comment]
This might be a good point of coordination with BlenderBIM.

**Comment by didimitrie** [comment]
A: Yes. Get the display mesh and attach the metadata to them - see Unity.

**Comment by didimitrie** [comment]
Upon actually reading this properly (sorry it took two weeks for this to actually sink in), we won't want to support the ***creation*** of built elements in Blender. It's too wild and far away.
