### ISSUE TITLE
Blender Plugin Activation Failed

### ISSUE THREAD

**Issue by tatenda-b** [specklesystems/speckle-blender#64]
On attempting to enable the plugin in blender after installing, the plugin throws a module not found error
![Capture](https://user-images.githubusercontent.com/46367854/142609462-e2f8832c-79cb-49f4-87f8-e1bedbf5efc9.PNG)

**Comment by izzylys** [comment]
hiya, thanks for reporting!

it sounds like `specklepy` didn't get installed for you for some reason, could you please look in the following folder and see if the `specklepy` folder is in there?
`AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modules`

if it's not, I would suggest uninstalling and reinstalling the plugin. you may need to launch blender twice to get everything to show up (bit if a bug that seems to happen to some people!).

if it still doesn't appear, there may be something wrong with the installer and we can debug this further!

**Comment by danielkleebinder** [comment]
Hello @izzylys 

I am currently working on a project that tries to integrate Speckle and I am getting the same error as mentioned above by @tatenda-b. I am using Windows 10 and for me, there is only the `bpy_speckle` folder in `AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\`. No modules. I used the SpeckleManager to install it.

I found your thread here: https://speckle.community/t/blender-no-module-named-specklepy/1320/4
and tried to follow the steps. Sadly, I am getting the following errors:

```
#9 74.58 Package operations: 34 installs, 0 updates, 0 removals
#9 74.58
#9 74.58   • Installing certifi (2021.10.8)
#9 74.58   • Installing charset-normalizer (2.0.7)
#9 74.58   • Installing idna (3.3)
#9 74.59   • Installing multidict (5.2.0)
#9 74.59   • Installing typing-extensions (4.0.0)
#9 74.59   • Installing urllib3 (1.26.7)
#9 76.42   • Installing async-timeout (3.0.1)
#9 76.42   • Installing attrs (21.2.0)
#9 76.43   • Installing chardet (4.0.0)
#9 76.43   • Installing requests (2.26.0)
#9 76.43   • Installing six (1.16.0)
#9 76.43   • Installing smmap (5.0.0)
#9 76.44   • Installing yarl (1.7.2)
#9 77.64   • Installing aiohttp (3.7.4.post0)
#9 77.64   • Installing gitdb (4.0.9)
#9 77.64   • Installing graphql-core (3.1.6)
#9 77.64   • Installing nose (1.3.7)
#9 77.64   • Installing python-dateutil (2.8.2)
#9 77.64   • Installing requests-toolbelt (0.9.1)
#9 77.64   • Installing websockets (9.1)
#9 80.06   • Installing appdirs (1.4.4)
#9 80.06   • Installing cmake (3.22.0)
#9 80.06   • Installing cmake-generators (1.0.9)
#9 80.06   • Installing distro (1.6.0)
#9 80.06   • Installing gitpython (3.1.24)
#9 80.06   • Installing gql (3.0.0b0)
#9 80.07   • Installing pydantic (1.8.2)
#9 80.07   • Installing svn (1.0.1)
#9 80.07   • Installing ujson (4.3.0)
#9 108.2   • Installing bpy (2.82.1)
#9 108.2   • Installing bpy-build (2.1.0)
#9 108.2   • Installing devtools (0.6.1)
#9 108.2   • Installing numpy (1.21.4)
#9 108.2   • Installing specklepy (2.4.0)
#9 109.1
#9 109.1   EnvCommandError
#9 109.1
#9 109.1   Command ['/app/.venv/bin/pip', 'install', '--no-deps', '/usr/local/lib/.cache/pypoetry/artifacts/c3/16/eb/6b98a6d1a55a006da46e3c027777424163225d828361554e2a1f3ad843/bpy-2.82.1.tar.gz'] errored with the following return code 1, and output:
#9 109.1   Processing /usr/local/lib/.cache/pypoetry/artifacts/c3/16/eb/6b98a6d1a55a006da46e3c027777424163225d828361554e2a1f3ad843/bpy-2.82.1.tar.gz
#9 109.1       ERROR: Command errored out with exit status 1:
#9 109.1        command: /app/.venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ht1101op/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ht1101op/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cd0etix4
#9 109.1            cwd: /tmp/pip-req-build-ht1101op/
#9 109.1       Complete output (16 lines):
#9 109.1       Traceback (most recent call last):
#9 109.1         File "/usr/local/lib/python3.7/tokenize.py", line 397, in find_cookie
#9 109.1           codec = lookup(encoding)
#9 109.1       LookupError: unknown encoding: future_fstrings
#9 109.1
#9 109.1       During handling of the above exception, another exception occurred:
#9 109.1
#9 109.1       Traceback (most recent call last):
#9 109.1         File "<string>", line 1, in <module>
#9 109.1         File "/usr/local/lib/python3.7/tokenize.py", line 449, in open
#9 109.1           encoding, lines = detect_encoding(buffer.readline)
#9 109.1         File "/usr/local/lib/python3.7/tokenize.py", line 436, in detect_encoding
#9 109.1           encoding = find_cookie(second)
#9 109.1         File "/usr/local/lib/python3.7/tokenize.py", line 405, in find_cookie
#9 109.1           raise SyntaxError(msg)
#9 109.1       SyntaxError: unknown encoding for '/tmp/pip-req-build-ht1101op/setup.py': future_fstrings
#9 109.1       ----------------------------------------
#9 109.1   WARNING: Discarding file:///usr/local/lib/.cache/pypoetry/artifacts/c3/16/eb/6b98a6d1a55a006da46e3c027777424163225d828361554e2a1f3ad843/bpy-2.82.1.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#9 109.1   ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#9 109.1   WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
#9 109.1   You should consider upgrading via the '/app/.venv/bin/python -m pip install --upgrade pip' command.
#9 109.1
#9 109.1
#9 109.1   at ~/.poetry/lib/poetry/utils/env.py:1183 in _run
#9 109.2       1179│                 output = subprocess.check_output(
#9 109.2       1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
#9 109.2       1181│                 )
#9 109.2       1182│         except CalledProcessError as e:
#9 109.2     → 1183│             raise EnvCommandError(e, input=input_)
#9 109.2       1184│
#9 109.2       1185│         return decode(output)
#9 109.2       1186│
#9 109.2       1187│     def execute(self, bin, *args, **kwargs):
#9 109.2
#9 ERROR: executor failed running [/bin/sh -c poetry update]: exit code: 1
```

**Comment by izzylys** [comment]
Hi @danielkleebinder,

Those instructions are outdated and will no longer work! This is because you now must install the dependencies with the python version packaged with your Blender version. You'll probably find it at
`C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.exe`

To install `specklepy` manually, you'll want to use this python version and install it into your blender modules folder at 
`C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin`

You can do this by running the following (replacing with your correct path):
```
C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin -m pip install --target="YOUR-USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\" specklepy==2.4.1"
```

**Comment by izzylys** [comment]
hey @tatenda-b and @danielkleebinder,

could you please confirm that following the steps for either

1. deleting the connector files and uninstalling and reinstalling 
2. manually installing `specklepy` into your blender environment

has resolved your issues? if so, I will go ahead and close this issue 😊

**Comment by vinnividivicci** [comment]
I seem to be running into the same issue activating the add-on:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/591242/144897397-ece7b4df-cc2d-4baa-84ea-0ed2e8f56291.png">
In my case I installed Blender 2.93 from the MS App Store, but maybe it's a related problem?

**Comment by izzylys** [comment]
hiya! thanks for reporting. have you tried the steps above for forcing a clean reinstall / installing `specklepy` manually?

interesting point about the MS app store though! I honestly hadn't considered people might be installing Blender from there, so this may be the source of the sudden influx of issues. I will have a dig into this today to investigate!

**Comment by vinnividivicci** [comment]
@izzylys Awesome! The latest update works for me with Blender 3.0 off the MS Store!

**Comment by izzylys** [comment]
fantastic, I'm glad to hear it @vinnividivicci!! thanks again for bringing the issue to my attention 😊

**Comment by izzylys** [comment]
hey @tatenda-b and @danielkleebinder!

I haven't heard back from you guys in a while, but the latest release 2.2.7 completely changes the installation process and in theory would fix any `specklepy` install issues you should be having. I am therefore considering this issue closed!

however, if you are still having issues then please feel free to reach out so we can investigate 😊
