### ISSUE TITLE
Error in loadind Speckle for Blender

### ISSUE THREAD

**Issue by Marco-Pellegrino** [specklesystems/speckle-blender#69]
![image](https://user-images.githubusercontent.com/53620289/144757084-1ada8499-761a-4479-b38a-5f5f96d6483c.png)

The error happen when I try to load speckle for Blender

**Comment by izzylys** [comment]
hiya! sorry you're having issues. can you please have a look at the thread under issue #64 and see if any of it applies to you? if not, please come back here and let me know what you tried so we can keep debugging this

**Comment by izzylys** [comment]
hey! this should have been fixed by v2.2.7 so I am closing this issue for now

however, if you're still having issues then please let me know so we can have another look! 😊

**Comment by Marco-Pellegrino** [comment]
thanks @izzylys 
I have solved the issue yesterday deleting and forcing to install a clean Speckle for Blender.
I was using Speckle to stream from Rhino and export with GLTB format.
Thanks for the help

**Comment by izzylys** [comment]
no problem! very happy to hear that you're up and running with it now 😊

if you have any more general questions as you're trying it out, feel free to reach out on [the forum](https://speckle.community/)!
