### ISSUE TITLE
👥 Accounts / Clients don't seem to be getting set up properly

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-blender#7]
The first account in my local db is showing up fine, but the rest (including my default one) don't seem to work when I select them in the dropdown. Seems like maybe only the first account has been added to `speckle_clients` ?

![image](https://user-images.githubusercontent.com/7717434/112631565-f67da000-8e2e-11eb-9c03-a640e24274d4.png)

**Comment by tsvilans** [comment]
Hmm... works here with 2 different accounts and switching between. Will investigate.
