### ISSUE TITLE
Converting Shader nodes to Speckle is hard-code limited to a single shader (Principled BSDF)

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-blender#82]
### Expected vs. Actual Behavior

Sending geometry using Emissive or Diffuse texture shader nodes fails as the Material Node isn't Principled.BSDF

### Reproduction Steps & System Config (win, osx, web, etc.)

macOS 12.2.1, Blender v3.0.1, byy_speckle 0.2.0 

![Screenshot 2022-02-22 at 22 28 49](https://user-images.githubusercontent.com/760691/155321584-1c57ac43-7161-4aa9-ab10-c47a67d743cb.png)

### Proposed Solution (if any)

I would add a List of Shader Nodes currently supported [as with Geometry and Curve types](https://github.com/specklesystems/speckle-blender/blob/8296e48c2879589ce7375d06e1b5c09e7fcbdcaf/bpy_speckle/convert/to_native.py#L16-L25) and wrap the [material conversion](https://github.com/specklesystems/speckle-blender/blob/c62538fc8f21cd54ca4ebdbec89d0f63067c46b1/bpy_speckle/convert/to_speckle.py#L251-L252) in a check for inclusion in that list.

#### Optional: Affected Projects

This is Blender specific. I'm happy to start a PR for the wrapper. 

Extending the supported shader conversions or even a fall-back to downgrade certain textures node types can follow later.

**Comment by AlanRynne** [comment]
Closing after connectors review chat!
