### ISSUE TITLE
🎥 Support for cameras/3D views

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-blender#84]
From the forum, to be discussed: https://speckle.community/t/support-for-blender-cameras/2404/3

**Comment by izzylys** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🎥 Cameras & Views](https://trello.com/c/PU8oTM5r/11-%F0%9F%8E%A5-cameras-views)

**Comment by izzylys** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🎥 cameras & views](https://trello.com/c/r3ibEtGt/8-%F0%9F%8E%A5-cameras-views)
