### ISSUE TITLE
🎨 Support for vertex colours

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-blender#94]
### Expected vs. Actual Behavior

We currently only support render materials. Vertex colours have also been requested!

https://speckle.community/t/mesh-colours-gh-to-blender/2931

https://speckle.xyz/streams/5e54e5bafb/commits/549b268b63

**Comment by JR-Morgan** [comment]
I've taken a look at implementing vertex colors ToSpeckle in Blender.
And I've run into another case where Blender aligns mesh attributes differently than our Mesh format expects.
Previously it was texture coordinates, this time it's vertex colors.

I fixed this previously by adding a `AlignVerticesWithTexCoordsByIndex` function to Mesh that restructures faces to map between blenders vertex instance indexing, and vertex indexing.
In order for me to add support for vertex colors in blender,
I may have to do the same thing now for colors. But I'm interested in looking at better ways we can handle this that doesn't require every connector to call this Align method

**Comment by fraguada** [comment]
Just ran into this sending a mesh with vertex colors from Rhino > Blender.

**Comment by tsvilans** [comment]
So in the very beginning of the SpeckleBlender add-on, there was a provision for pulling in vertex colors into Blender. If a mesh object had a property `colors` the same length as its vertex list, then these would be translated into vertex colors in Blender. The list of colors would be encoded as a single `int32` for every color, interpreted as 4 bytes (ARGB).

The function is still there: https://github.com/specklesystems/speckle-blender/blob/fbda0110cd53201bd4e57e605c055c53bf6c6cca/bpy_speckle/convert/util.py#L154

I unfortunately have been away from the party for a while, so I'm not sure if that has changed, or what the receiving code now looks like, but maybe that helps whoever oversees this now.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
